### ISSUE TITLE
update compile options

### ISSUE THREAD

**Issue by cbcoutinho** [Fortran-FOSS-Programmers/FOODIE#37]
The currently compile steps do not reflect the current state of the project:

`FoBiS.py build -lmodes` does not result in:

```
The fobos file defines the following modes:
  - "shared-gnu"
  - "shared-intel"
  - "static-gnu"
  - "static-intel"
  - "tests-gnu"
  - "tests-intel"
  - "tests-gnu-debug"
  - "tests-intel-debug"
```

as stated in the docs. On openSUSE 42.1 with gfortran 5.3.1, I get:

```
The fobos file defines the following modes:
  - "foodie-static-opencoarrays-gnu" Build FOODIE library in static release mode with OpenCoarrays-GNU gfortran
  - "foodie-static-opencoarrays-gnu-debug" Build FOODIE library in static release mode with OpenCoarrays-GNU gfortran
  - "foodie-static-gnu" Build FOODIE library in static release mode with GNU gfortran
  - "foodie-static-gnu-debug" Build FOODIE library in static debug mode with GNU gfortran
  - "foodie-shared-gnu" Build FOODIE library in shared release mode with GNU gfortran
  - "foodie-shared-gnu-debug" Build FOODIE library in shared debug mode with GNU gfortran
  - "foodie-static-intel" Build FOODIE library in static release mode with Intel Fortran
  - "foodie-static-intel-debug" Build FOODIE library in static debug mode with Intel Fortran
  - "foodie-shared-intel" Build FOODIE library in shared release mode with Intel Fortran
  - "foodie-shared-intel-debug" Build FOODIE library in shared debug mode with Intel Fortran
  - "foodie-static-gnu-coverage" Build FOODIE library in static release coverage mode with GNU gfortran
  - "foodie-static-gnu-pure" Build FOODIE library in static release mode with GNU gfortran
  - "foodie-static-gnu-debug-pure" Build FOODIE library in static debug mode with GNU gfortran
  - "foodie-static-gnu-coverage-pure" Build FOODIE library in static release coverage mode with GNU gfortran
  - "foodie-static-intel-pure" Build FOODIE library in static release mode with Intel Fortran
  - "foodie-static-intel-debug-pure" Build FOODIE library in static debug mode with Intel Fortran
```

Should the docs be updated to reflect this or is it compiler specific? I updated the wiki myself, but further explanation from a maintainer is probably helpful

**Comment by szaghi** [comment]
@cbcoutinho Dear Chris, you are right! the doc is surely not up-to-date... unfortunately in the last months I had not time for FOODIE :cry: 

I hope to update it soon.

**Comment by cbcoutinho** [comment]
Also the tests don't work, when trying to run the oscillations test I get a fobos file error - I think the two were updated out of sync. When I have more time to look at how FoBiS.py works I can try to make changes and an associated a PR.

Apparently the FoBiS.py project build mode is overriding the only available modes for the test, bummer man.

```
> FoBiS.py build -mode gnu-coverage
Module 'pygooglechart' not found: Gcov graphs disabled
Warning: found optimizations cflags within coverage ones: coverage results can be alterated!
Warning: found optimizations lflags within coverage ones: coverage results can be alterated!
The present cflags are different from the heritages one: forcing to (re-)compile all
Building dependency fobos into . with mode foodie-static-gnu-coverage
Module 'pygooglechart' not found: Gcov graphs disabled
Error: the mode "foodie-static-gnu-coverage" is not defined into the fobos file.
The fobos file defines the following modes:
  - "gnu" Build test in release mode with GNU gfortran
  - "gnu-debug" Build test in debug mode with GNU gfortran
  - "gnu-coverage" Build test in release coverage mode with GNU gfortran
  - "intel" Build test in release mode with Intel Fortran
  - "intel-debug" Build test in debug mode with Intel Fortran
  - "errors-analysis" Build test in release mode (for errors analysis) with GNU gfortran
  - "gnu-pure" Build test in release mode with GNU gfortran
  - "gnu-debug-pure" Build test in debug mode with GNU gfortran
  - "gnu-coverage-pure" Build test in release coverage mode with GNU gfortran
  - "intel-pure" Build test in release mode with Intel Fortran
  - "intel-debug-pure" Build test in debug mode with Intel Fortran

Traceback (most recent call last):
  File "/usr/bin/FoBiS.py", line 21, in <module>
    main()
  File "/usr/lib/python3.4/site-packages/fobis/fobis.py", line 39, in main
    run_fobis()
  File "/usr/lib/python3.4/site-packages/fobis/fobis.py", line 52, in run_fobis
    configuration = FoBiSConfig(fake_args=fake_args)
  File "/usr/lib/python3.4/site-packages/fobis/FoBiSConfig.py", line 60, in __init__
    self._postinit()
  File "/usr/lib/python3.4/site-packages/fobis/FoBiSConfig.py", line 122, in _postinit
    self._check_interdependent_fobos()
  File "/usr/lib/python3.4/site-packages/fobis/FoBiSConfig.py", line 289, in _check_interdependent_fobos
    os.chdir(os.path.join(old_pwd, fobos_path))
FileNotFoundError: [Errno 2] No such file or directory: '/home/user/Projects/FOODIE/src/tests/accuracy/oscillation/./src/third_party'
```

**Comment by szaghi** [comment]
@cbcoutinho I am very sorry, but the doc is really outdated. If you want to run the oscillation test you should run FoBiS with the following options:

``` shell
stefano@zaghi(04:42 PM Fri Oct 21) on master [?]
~/fortran/FOODIE 21 files, 184Kb
→ FoBiS.py build -f src/tests/accuracy/oscillation/fobos 
Building dependency fobos into . with mode foodie-static-gnu
Builder options
  Directories
    Building directory: "build/lib"
    Compiled-objects .o   directory: "build/lib/obj"
    Compiled-objects .mod directory: "build/lib/mod"
  Compiler options
    Vendor: "gnu"
    Compiler command: "gfortran"
    Module directory switch: "-J"
    Compiling flags: "-cpp -c -frealloc-lhs -O2"
    Linking flags: "-O2"
    Preprocessing flags: ""
    Coverage: False
    Profile: False
  PreForM.py used: False
  PreForM.py output directory: None
  PreForM.py extensions processed: []

Building src/lib/foodie.f90
Compiling src/lib/foodie_kinds.f90 serially
Compiling src/lib/foodie_adt_integrand.f90 src/lib/foodie_utils.f90 using 2 concurrent processes
Compiling src/lib/foodie_integrator_adams_bashforth.f90 src/lib/foodie_integrator_adams_moulton.f90 using 2 concurrent processes
Compiling src/lib/foodie_integrator_adams_bashforth_moulton.f90 src/lib/foodie_integrator_backward_differentiation_formula.f90 src/lib/foodie_integrator_embedded_runge_kutta.f90 src/lib/foodie_integrator_euler_explicit.f90 src/lib/foodie_integrator_leapfrog.f90 src/lib/foodie_integrator_low_storage_runge_kutta.f90 src/lib/foodie_integrator_tvd_runge_kutta.f90 using 7 concurrent processes
Compiling src/lib/foodie.f90 serially
Linking build/lib/libfoodie.a
Target src/lib/foodie.f90 has been successfully built

Building dependency fobos into ./src/third_party with mode flap-static-gnu
Builder options
  Directories
    Building directory: "lib/flap"
    Compiled-objects .o   directory: "lib/flap/obj"
    Compiled-objects .mod directory: "lib/flap/mod"
  Compiler options
    Vendor: "gnu"
    Compiler command: "gfortran"
    Module directory switch: "-J"
    Compiling flags: "-cpp -c -frealloc-lhs -O2"
    Linking flags: ""
    Preprocessing flags: ""
    Coverage: False
    Profile: False
  PreForM.py used: False
  PreForM.py output directory: None
  PreForM.py extensions processed: []

Building FLAP/src/lib/flap.f90
Nothing to compile, all objects are up-to-date
Linking lib/flap/libflap.a
Target FLAP/src/lib/flap.f90 has been successfully built

Building dependency fobos into ./src/third_party with mode pyplot-fortran-static-gnu
Builder options
  Directories
    Building directory: "lib/pyplot-fortran"
    Compiled-objects .o   directory: "lib/pyplot-fortran/obj"
    Compiled-objects .mod directory: "lib/pyplot-fortran/mod"
  Compiler options
    Vendor: "gnu"
    Compiler command: "gfortran"
    Module directory switch: "-J"
    Compiling flags: "-cpp -c -frealloc-lhs -O2"
    Linking flags: ""
    Preprocessing flags: ""
    Coverage: False
    Profile: False
  PreForM.py used: False
  PreForM.py output directory: None
  PreForM.py extensions processed: []

Building pyplot-fortran/src/pyplot_module.f90
Nothing to compile, all objects are up-to-date
Linking lib/pyplot-fortran/libpyplot.a
Target pyplot-fortran/src/pyplot_module.f90 has been successfully built

Building dependency fobos into ./src/third_party with mode wenoof-static-gnu
Builder options
  Directories
    Building directory: "lib/wenoof"
    Compiled-objects .o   directory: "lib/wenoof/obj"
    Compiled-objects .mod directory: "lib/wenoof/mod"
  Compiler options
    Vendor: "gnu"
    Compiler command: "gfortran"
    Module directory switch: "-J"
    Compiling flags: "-cpp -c -frealloc-lhs -O2"
    Linking flags: ""
    Preprocessing flags: ""
    Coverage: False
    Profile: False
  PreForM.py used: False
  PreForM.py output directory: None
  PreForM.py extensions processed: []

Building WenOOF/src/lib/wenoof.f90
Nothing to compile, all objects are up-to-date
Linking lib/wenoof/libwenoof.a
Target WenOOF/src/lib/wenoof.f90 has been successfully built

The following auxiliary paths have been added
Include files search paths (include):
- build/lib/mod
- src/third_party/lib/flap/mod
- src/third_party/lib/pyplot-fortran/mod
- src/third_party/lib/wenoof/mod
Libraries search paths (lib_dir):
Libraries paths:
- (libs) build/lib/libfoodie.a
- (libs) src/third_party/lib/flap/libflap.a
- (libs) src/third_party/lib/pyplot-fortran/libpyplot.a
- (libs) src/third_party/lib/wenoof/libwenoof.a
Builder options
  Directories
    Building directory: "build/tests/accuracy/oscillation"
    Compiled-objects .o   directory: "build/tests/accuracy/oscillation/obj"
    Compiled-objects .mod directory: "build/tests/accuracy/oscillation/mod"
  Included paths: build/lib/mod src/third_party/lib/flap/mod src/third_party/lib/pyplot-fortran/mod src/third_party/lib/wenoof/mod
  Linked libraries with full path: build/lib/libfoodie.a src/third_party/lib/flap/libflap.a src/third_party/lib/pyplot-fortran/libpyplot.a src/third_party/lib/wenoof/libwenoof.a
  Compiler options
    Vendor: "gnu"
    Compiler command: "gfortran"
    Module directory switch: "-J"
    Compiling flags: "-cpp -c -frealloc-lhs -O2"
    Linking flags: "-O2"
    Preprocessing flags: ""
    Coverage: False
    Profile: False
  PreForM.py used: False
  PreForM.py output directory: None
  PreForM.py extensions processed: []

Building src/tests/accuracy/oscillation/oscillation.f90
Compiling src/tests/accuracy/oscillation/oscillation_t.f90 serially
Compiling src/tests/accuracy/oscillation/oscillation.f90 serially
Linking build/tests/accuracy/oscillation/oscillation
Target src/tests/accuracy/oscillation/oscillation.f90 has been successfully built
```

**Comment by cbcoutinho** [comment]
I just re-cloned the repo and I'm still getting an error trying to build the tests. Am I only having issues with pygooglechart? It seems that project is no longer being maintained.

```
chris@host:~/Projects/FOODIE> FoBiS.py build -f src/tests/accuracy/oscillation/fobos
Module 'pygooglechart' not found: Gcov graphs disabled
Building dependency fobos into . with mode foodie-static-gnu
Module 'pygooglechart' not found: Gcov graphs disabled
Builder options
  Directories
    Building directory: "build/lib"
    Compiled-objects .o   directory: "build/lib/obj"
    Compiled-objects .mod directory: "build/lib/mod"
  Compiler options
    Vendor: "gnu"
    Compiler command: "gfortran"
    Module directory switch: "-J"
    Compiling flags: "-cpp -c -frealloc-lhs -O2"
    Linking flags: "-O2"
    Preprocessing flags: ""
    Coverage: False
    Profile: False
  PreForM.py used: False
  PreForM.py output directory: None
  PreForM.py extensions processed: []

Building src/lib/foodie.f90
Compiling src/lib/foodie_kinds.f90 serially
Compiling src/lib/foodie_adt_integrand.f90 src/lib/foodie_utils.f90 using 2 concurrent processes
Compiling src/lib/foodie_integrator_adams_bashforth.f90 src/lib/foodie_integrator_adams_moulton.f90 using 2 concurrent processes
Compiling src/lib/foodie_integrator_adams_bashforth_moulton.f90 src/lib/foodie_integrator_backward_differentiation_formula.f90 src/lib/foodie_integrator_embedded_runge_kutta.f90 src/lib/foodie_integrator_euler_explicit.f90 src/lib/foodie_integrator_leapfrog.f90 src/lib/foodie_integrator_low_storage_runge_kutta.f90 src/lib/foodie_integrator_tvd_runge_kutta.f90 using 7 concurrent processes
Compiling src/lib/foodie.f90 serially
Linking build/lib/libfoodie.a
Target src/lib/foodie.f90 has been successfully built

Building dependency fobos into ./src/third_party with mode flap-static-gnu
Module 'pygooglechart' not found: Gcov graphs disabled
Builder options
  Directories
    Building directory: "lib/flap"
    Compiled-objects .o   directory: "lib/flap/obj"
    Compiled-objects .mod directory: "lib/flap/mod"
  Compiler options
    Vendor: "gnu"
    Compiler command: "gfortran"
    Module directory switch: "-J"
    Compiling flags: "-cpp -c -frealloc-lhs -O2"
    Linking flags: ""
    Preprocessing flags: ""
    Coverage: False
    Profile: False
  PreForM.py used: False
  PreForM.py output directory: None
  PreForM.py extensions processed: []

Building FLAP/src/lib/flap.f90
Compiling FLAP/src/third_party/PENF/src/lib/penf.F90 serially
Compiling FLAP/src/lib/flap_object_t.f90 FLAP/src/lib/flap_utils_m.f90 using 2 concurrent processes
Compiling FLAP/src/lib/flap_command_line_argument_t.F90 serially
Compiling FLAP/src/lib/flap_command_line_arguments_group_t.f90 serially
Compiling FLAP/src/lib/flap_command_line_interface_t.F90 serially
Compiling FLAP/src/lib/flap.f90 serially
Linking lib/flap/libflap.a
Target FLAP/src/lib/flap.f90 has been successfully built

Building dependency fobos into ./src/third_party with mode pyplot-fortran-static-gnu
Module 'pygooglechart' not found: Gcov graphs disabled
Builder options
  Directories
    Building directory: "lib/pyplot-fortran"
    Compiled-objects .o   directory: "lib/pyplot-fortran/obj"
    Compiled-objects .mod directory: "lib/pyplot-fortran/mod"
  Compiler options
    Vendor: "gnu"
    Compiler command: "gfortran"
    Module directory switch: "-J"
    Compiling flags: "-cpp -c -frealloc-lhs -O2"
    Linking flags: ""
    Preprocessing flags: ""
    Coverage: False
    Profile: False
  PreForM.py used: False
  PreForM.py output directory: None
  PreForM.py extensions processed: []

Building pyplot-fortran/src/pyplot_module.f90
Compiling pyplot-fortran/src/pyplot_module.f90 serially
Linking lib/pyplot-fortran/libpyplot.a
Target pyplot-fortran/src/pyplot_module.f90 has been successfully built

Building dependency fobos into ./src/third_party with mode wenoof-static-gnu
Module 'pygooglechart' not found: Gcov graphs disabled
Builder options
  Directories
    Building directory: "lib/wenoof"
    Compiled-objects .o   directory: "lib/wenoof/obj"
    Compiled-objects .mod directory: "lib/wenoof/mod"
  Compiler options
    Vendor: "gnu"
    Compiler command: "gfortran"
    Module directory switch: "-J"
    Compiling flags: "-cpp -c -frealloc-lhs -O2"
    Linking flags: ""
    Preprocessing flags: ""
    Coverage: False
    Profile: False
  PreForM.py used: False
  PreForM.py output directory: None
  PreForM.py extensions processed: []

Building WenOOF/src/lib/wenoof.f90
Compiling WenOOF/src/third_party/PENF/src/lib/penf.F90 serially
Compiling WenOOF/src/lib/type_weno_interpolator.f90 serially
Compiling WenOOF/src/lib/type_weno_interpolator_upwind.f90 serially
Compiling WenOOF/src/lib/wenoof.f90 serially
Linking lib/wenoof/libwenoof.a
Target WenOOF/src/lib/wenoof.f90 has been successfully built

The following auxiliary paths have been added
Include files search paths (include):
- Module 'pygooglechart' not found: Gcov graphs disabled
./build/lib/Module 'pygooglechart' not found: Gcov graphs disabled
mod
- src/third_party/Module 'pygooglechart' not found: Gcov graphs disabled
./lib/flap/Module 'pygooglechart' not found: Gcov graphs disabled
./mod
- src/third_party/Module 'pygooglechart' not found: Gcov graphs disabled
./lib/pyplot-fortran/Module 'pygooglechart' not found: Gcov graphs disabled
./mod
- src/third_party/Module 'pygooglechart' not found: Gcov graphs disabled
./lib/wenoof/Module 'pygooglechart' not found: Gcov graphs disabled
./mod
Libraries search paths (lib_dir):
Libraries paths:
- (libs) Module 'pygooglechart' not found: Gcov graphs disabled
build/lib/libfoodie.a
- (libs) src/third_party/Module 'pygooglechart' not found: Gcov graphs disabled
lib/flap/libflap.a
- (libs) src/third_party/Module 'pygooglechart' not found: Gcov graphs disabled
lib/pyplot-fortran/libpyplot.a
- (libs) src/third_party/Module 'pygooglechart' not found: Gcov graphs disabled
lib/wenoof/libwenoof.a
Attention: the file 'src/tests/accuracy/oscillation/oscillation.f90' depends on 'flap' that is unreachable
Attention: the file 'src/tests/accuracy/oscillation/oscillation.f90' depends on 'foodie' that is unreachable
Attention: the file 'src/tests/accuracy/oscillation/oscillation.f90' depends on 'penf' that is unreachable
Attention: the file 'src/tests/accuracy/oscillation/oscillation.f90' depends on 'pyplot_module' that is unreachable
Attention: the file 'src/tests/accuracy/oscillation/oscillation_t.f90' depends on 'foodie' that is unreachable
Attention: the file 'src/tests/accuracy/oscillation/oscillation_t.f90' depends on 'penf' that is unreachable
Builder options
  Directories
    Building directory: "build/tests/accuracy/oscillation"
    Compiled-objects .o   directory: "build/tests/accuracy/oscillation/obj"
    Compiled-objects .mod directory: "build/tests/accuracy/oscillation/mod"
  Included paths: Module 'pygooglechart' not found: Gcov graphs disabled
./build/lib/Module 'pygooglechart' not found: Gcov graphs disabled
mod src/third_party/Module 'pygooglechart' not found: Gcov graphs disabled
./lib/flap/Module 'pygooglechart' not found: Gcov graphs disabled
./mod src/third_party/Module 'pygooglechart' not found: Gcov graphs disabled
./lib/pyplot-fortran/Module 'pygooglechart' not found: Gcov graphs disabled
./mod src/third_party/Module 'pygooglechart' not found: Gcov graphs disabled
./lib/wenoof/Module 'pygooglechart' not found: Gcov graphs disabled
./mod 
  Linked libraries with full path: Module 'pygooglechart' not found: Gcov graphs disabled
build/lib/libfoodie.a src/third_party/Module 'pygooglechart' not found: Gcov graphs disabled
lib/flap/libflap.a src/third_party/Module 'pygooglechart' not found: Gcov graphs disabled
lib/pyplot-fortran/libpyplot.a src/third_party/Module 'pygooglechart' not found: Gcov graphs disabled
lib/wenoof/libwenoof.a 
  Compiler options
    Vendor: "gnu"
    Compiler command: "gfortran"
    Module directory switch: "-J"
    Compiling flags: "-cpp -c -frealloc-lhs -O2"
    Linking flags: "-O2"
    Preprocessing flags: ""
    Coverage: False
    Profile: False
  PreForM.py used: False
  PreForM.py output directory: None
  PreForM.py extensions processed: []

Building src/tests/accuracy/oscillation/oscillation.f90
Compiling src/tests/accuracy/oscillation/oscillation_t.f90 serially
gfortran: error: pygooglechart: No such file or directory
gfortran: error: not: No such file or directory
gfortran: error: found:: No such file or directory
gfortran: error: Gcov: No such file or directory
gfortran: error: graphs: No such file or directory
gfortran: error: disabled: No such file or directory
gfortran: fatal error: no input files
compilation terminated.
/bin/sh: line 1: ./build/lib/Module: No such file or directory
/bin/sh: line 2: mod: command not found
/bin/sh: line 3: ./lib/flap/Module: No such file or directory
/bin/sh: line 4: ./mod: No such file or directory
/bin/sh: line 5: ./lib/pyplot-fortran/Module: No such file or directory
/bin/sh: line 6: ./mod: No such file or directory
/bin/sh: line 7: ./lib/wenoof/Module: No such file or directory
/bin/sh: line 8: ./mod: No such file or directory

gfortran: error: pygooglechart: No such file or directory
gfortran: error: not: No such file or directory
gfortran: error: found:: No such file or directory
gfortran: error: Gcov: No such file or directory
gfortran: error: graphs: No such file or directory
gfortran: error: disabled: No such file or directory
gfortran: fatal error: no input files
compilation terminated.
/bin/sh: line 1: ./build/lib/Module: No such file or directory
/bin/sh: line 2: mod: command not found
/bin/sh: line 3: ./lib/flap/Module: No such file or directory
/bin/sh: line 4: ./mod: No such file or directory
/bin/sh: line 5: ./lib/pyplot-fortran/Module: No such file or directory
/bin/sh: line 6: ./mod: No such file or directory
/bin/sh: line 7: ./lib/wenoof/Module: No such file or directory
/bin/sh: line 8: ./mod: No such file or directory
```

**Comment by szaghi** [comment]
@cbcoutinho 

Dear Chris, for building the tests you have not only to clone the repo, but also all submodules. I was sure you have all dependencies, sorry for my mistakes. To be sure to have all you need, try the following

``` shell
git clone --recursive https.../FOODIE
cd FOODIE
git submodule update --init --recursive
```

After this commands (I shorted the url, insert the correct path) you should have all you need to build the tests. 

Pygooglechart I a python module used by FoBiS to generate nice coverage reports. I know is now unmaintained, but I never find the time to switch to other modules. You can ignore that warning safely.

Good night, see you tomorrow.

**Comment by rouson** [comment]
I recommend that every time an issue like this is encountered, the solution gets captured in even a minimalistic script that simply contains the required steps. For every one user who reports the issue, there are surely 10 or more who don’t report it and go away silently.

Damian

**Comment by szaghi** [comment]
@rouson Damian, I totally agree, I am working the installer (on the basis of the FLAP's one). Unfortunately, these days are very busy (the first open call is very close...), but soon I'll fix it.

Cheers.
